#Autogenerated by ReportLab guiedit do not edit
from reportlab.graphics.charts.legends import Legend
from reportlab.lib.colors import Color, black, PCMYKColor, toColor, red, pink, blue
from reportlab.graphics.charts.textlabels import Label
from reportlab.graphics.charts.lineplots import SimpleTimeSeriesPlot
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin, Rect

class FundIndexLinePlot(_DrawingEditorMixin,Drawing):
    def __init__(self,width=355,height=100,*args,**kw):
        Drawing.__init__(self,width,height,*args,**kw)
        self._add(self,SimpleTimeSeriesPlot(),name='chart',validate=None,desc=None)
        self.chart.yValueAxis.visibleGrid             = 1
        self.chart.xValueAxis.labels.angle            = 45
        self.chart.xValueAxis.labels.boxAnchor='ne'
        self._add(self,Legend(),name='legend',validate=None,desc=None)
        self.legend.dy               = 5
        self.legend.dx               = 5
        self.legend.alignment='right'
        self.legend.variColumn       = 1
        self.legend.dxTextSpace      = 3
        self.legend.strokeColor      = None
        self.chart.yValueAxis.forceZero               = 0
        self.chart.yValueAxis.visibleTicks            = 0
        self.chart.yValueAxis.rangeRound='both'
        self.chart.yValueAxis.gridStrokeWidth         = 1
        self.chart.xValueAxis.labels.fontName         = 'Helvetica'
        self.chart.xValueAxis.dailyFreq = True
        self.chart.yValueAxis.labels.fontName         = 'Helvetica'
        self.legend.fontName       = 'Helvetica'
        self.height      = 110
        self.width       = 355
        self.legend.fontSize         = 6.5
        self.chart.xValueAxis.labels.fontSize         = 6.5
        self.chart.yValueAxis.visibleAxis             = 1
        self.chart.yValueAxis.visibleSubGrid          = 0
        self.chart.yValueAxis.labels.fontSize         = 6.5
        self.chart.strokeWidth      = 1
        self.chart.fillColor        = PCMYKColor(0,0,0,5,alpha=100)
        self.chart.lines.strokeWidth     = 1
        self.chart.gridFirst        = 0
        self.chart.behindAxes       = 0
        self.chart.y                = 0
        self.chart.strokeColor      = PCMYKColor(0,0,0,5)
        self.chart.height           = 100
        self.chart.width            = 270
        self.chart.yValueAxis.strokeColor             = PCMYKColor(9,0.5,2,20,alpha=100)
        self.chart.xValueAxis.strokeColor             = PCMYKColor(9,0.5,2,20,alpha=100)
        self.chart.yValueAxis.labels.rightPadding   = 10
        self.chart.yValueAxis.skipEndL                = 'none'
        self.chart.yValueAxis.subGridStrokeLineCap    = 0
        self.chart.xValueAxis.gridStart               = 0
        self.chart.xValueAxis.gridEnd                 = 0
        self.chart.xValueAxis.gridStrokeWidth         = 1
        self.chart.xValueAxis.visibleGrid             = 1
        self.chart.xValueAxis.subGridStrokeColor      = PCMYKColor(9,.5,2,20,alpha=100)
        self.chart.xValueAxis.gridStrokeColor         = PCMYKColor(9,0.5,2,20,alpha=100)
        self.chart.yValueAxis.gridStrokeColor       = PCMYKColor(9,0.5,2,20,alpha=100)
        self._add(self,Label(),name='title',validate=None,desc=None)
        self.title.x                = 180
        self.title._text            = ''
        self.title.fontSize         = 8.5
        self.title.y                = 145
        self._add(self,Label(),name='yAxisLabel',validate=None,desc=None)
        self.chart.x                = 50.0
        self.yAxisLabel._text            = '% GROWTH'
        self.yAxisLabel.fontSize         = 6.5
        self.yAxisLabel.angle            = 90
        self.yAxisLabel.x                = 10
        self.yAxisLabel.y                = 60
        self.legend.colorNamePairs   = [(PCMYKColor(100,0,8,13,alpha=100), 'line1'), (PCMYKColor(90,5,20,80,alpha=100), 'line2'), (Color(0,.501961,0,1), 'line3')]
        self.chart.lines[0].strokeColor = PCMYKColor(100,0,8,13)
        self.chart.lines[1].strokeColor = PCMYKColor(90,5,20,80)
        self.chart.lines[2].strokeColor = Color(0,.501961,0,1)
        self.legend.columnMaximum    = 1
        self.legend.x                = 35
        self.yAxisLabel.fontName         = 'Helvetica'
        self.chart.xValueAxis.xLabelFormat            = '{mmm} {yyyy}'
        self.chart.xValueAxis.labels.x                = 0
        self.chart.xValueAxis.labels.y                = 0
        self.chart.xValueAxis.visibleTicks            = 1
        self.chart.xValueAxis.labelAxisMode           = 'axis'
        self.chart.xValueAxis.labels.dx               = 0
        self.chart.xValueAxis.labels.dy               = -5
        self.legend.y                = -35
        self.chart.yValueAxis.labelTextFormat         = '%d'



if __name__=="__main__": #NORUNTESTS
    FundIndexLinePlot().save(formats=['pdf'],outDir='.',fnRoot=None)
