
## download data from CPHSDC
months = range(1, 13)
Months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
diseaseRawIds = range(1, 1000)

# translate province name to English
provinceName2Code = {
    '全国': 'Total',
    '北京': 'Beijing',
    '天津': 'Tianjin',
    '河北': 'Hebei',
    '山西': 'Shanxi',
    '山东': 'Shandong',
    '内蒙古': 'Inner Mongolia',
    '辽宁': 'Liaoning',
    '吉林': 'Jilin',
    '黑龙江': 'Heilongjiang',
    '上海': 'Shanghai',
    '江苏': 'Jiangsu',
    '浙江': 'Zhejiang',
    '安徽': 'Anhui',
    '福建': 'Fujian',
    '江西': 'Jiangxi',
    '山东': 'Shandong',
    '河南': 'Henan',
    '湖北': 'Hubei',
    '湖南': 'Hunan',
    '广东': 'Guangdong',
    '广西': 'Guangxi',
    '海南': 'Hainan',
    '重庆': 'Chongqing',
    '四川': 'Sichuan',
    '贵州': 'Guizhou',
    '云南': 'Yunnan',
    '西藏': 'Tibet',
    '陕西': 'Shaanxi',
    '甘肃': 'Gansu',
    '青海': 'Qinghai',
    '宁夏': 'Ningxia',
    '新疆': 'Xinjiang',
    '台湾': 'Taiwan',
    '香港': 'Hong Kong',
    '澳门': 'Macao'
    }

# translate province name to ADCode
provinceName2ADCode = {
    '全国': '100000',
    '北京': '110000',
    '天津': '120000',
    '河北': '130000',
    '山西': '140000',
    '内蒙古': '150000',
    '辽宁': '210000',
    '吉林': '220000',
    '黑龙江': '230000',
    '上海': '310000',
    '江苏': '320000',
    '浙江': '330000',
    '安徽': '340000',
    '福建': '350000',
    '江西': '360000',
    '山东': '370000',
    '河南': '410000',
    '湖北': '420000',
    '湖南': '430000',
    '广东': '440000',
    '广西': '450000',
    '海南': '460000',
    '重庆': '500000',
    '四川': '510000',
    '贵州': '520000',
    '云南': '530000',
    '西藏': '540000',
    '陕西': '610000',
    '甘肃': '620000',
    '青海': '630000',
    '宁夏': '640000',
    '新疆': '650000',
    '台湾': '710000',
    '香港': '810000',
    '澳门': '820000'
}

## translate disease name to English
diseaseName2Code = {
    '鼠疫': 'Plague',
    '霍乱': 'Cholera',
    '痢疾': 'Dysentery',
    '细菌性痢疾': 'Bacterial dysentery',
    '阿米巴痢疾': 'Amoebic dysentery',
    '阿米巴性痢疾': 'Amoebic dysentery',
    '伤寒': 'Typhoid',
    '副伤寒': 'Paratyphoid',
    '伤寒和副伤寒': 'Typhoid fever and paratyphoid fever',
    '伤寒+副伤寒': 'Typhoid fever and paratyphoid fever',
    '艾滋病': 'Acquired immune deficiency syndrome',
    'ＨＩＶ': 'HIV',
    '淋病': 'Gonorrhea',
    '梅毒': 'Syphilis',
    'Ⅲ期梅毒': 'Tertiary syphilis',
    'III期梅毒': 'Tertiary syphilis',
    'Ⅱ期梅毒': 'Secondary syphilis',
    'II期梅毒': 'Secondary syphilis',
    'Ⅰ期梅毒': 'Primary syphilis',
    '胎传梅毒': 'Congenital syphilis',
    '隐性梅毒': 'Latent syphilis',
    '疟疾': 'Malaria',
    '麻疹': 'Measles',
    '百日咳': 'Pertussis',
    '流脑': 'Meningococcal meningitis',
    '猩红热': 'Scarlet fever',
    '出血热': 'Epidemic hemorrhagic fever',
    '狂犬病': 'Rabies',
    '钩体病': 'Leptospirosis',
    '布病': 'Brucellosis',
    '炭疽': 'Anthrax',
    '炭疽（未分型）': 'Anthrax (unclassified)',
    '肺炭疽': 'Pulmonary anthrax',
    '新生儿破伤风': 'Neonatal tetanus',
    '斑疹伤寒': 'Typhus',
    '黑热病': 'Kala azar',
    '恶性疟': 'Malignant malaria',
    '间日疟': 'Tertian malaria',
    '疟疾（未分型）': 'Malaria (unclassified)',
    '乙脑': 'Japanese encephalitis',
    '登革热': 'Dengue',
    '肺结核': 'Tuberculosis',
    '菌（-）': 'Tuberculosis (negative)',
    '菌（+）': 'Tuberculosis (positive)',
    '涂（+）': 'Tuberculosis (acid-fast positive)',
    '仅培阳': 'Tuberculosis (positive)',
    '未痰检': 'Tuberculosis (unclassified)',
    '利福平耐药': 'Tuberculosis (rifampicin-resistant)',
    '无病原学结果': 'Tuberculosis (unclassified)',
    '病原学阳性': 'Tuberculosis (positive)',
    '病原学阴性': 'Tuberculosis (negative)',
    '血吸虫病': 'Schistosomiasis',
    '包虫病': 'Echinococcosis',
    '麻风病': 'Leprosy',
    '流行性感冒': 'Influenza',
    '流行性腮腺炎': 'Mumps',
    '风疹': 'Rubella',
    '非淋菌性尿道炎': 'Nongonococcal urethritis',
    '其它感染性腹泻病': 'Infectious diarrhea',
    '急性出血性结膜炎': 'Acute hemorrhagic conjunctivitis',
    '尖锐湿疣': 'Condyloma acuminatum',
    '生殖器疱疹': 'Genital herpes',
    '手足口病': 'Hand foot and mouth disease',
    '皮肤炭疽': 'Cutaneous anthrax',
    '其它': 'Other',
    '甲肝': 'Hepatitis A',
    '乙肝': 'Hepatitis B',
    '丙肝': 'Hepatitis C',
    '丁肝': 'Hepatitis D',
    '戊肝': 'Hepatitis E',
    '肝炎（未分型）': 'Other hepatitis',
    '肝炎': 'Hepatitis',
    '水痘': 'Chickenpox',
    '人感染猪链球菌': 'Streptococcus suis',
    '生殖道沙眼衣原体感染': 'Chlamydia trachomatis',
    '肝吸虫病': 'Fascioliasis',
    '恙虫病': 'Typhus',
    '脊灰': 'Poliomyelitis',
    '白喉': 'Diphtheria',
    '非典临床诊断': 'SARS-CoV',
    '非典（临床诊断）': 'SARS-CoV',
    '不明原因肺炎': 'Unknown pneumonia',
    '不明原因': 'Unknown pneumonia',
    '丝虫病': 'Filariasis',
    '森林脑炎': 'Tick-borne encephalitis',
    '人粒细胞无形体病': 'Human granulocytic anaplasmosis'
}

# setting correct
diseaseIds = [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 
              26, 27, 28, 29, 30, 31, 40, 45, 120, 121, 122, 123, 124, 125, 
              126, 127, 128, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 
              145, 147, 160, 198, 199, 200, 201, 204, 205, 206, 220, 240, 241, 
              243, 318, 319, 320, 321, 322, 323, 324, 346, 347, 366, 367, 368]