
## 转换疾病名称到英文
diseaseCode2Name = {
    'Plague': '鼠疫',
    'Cholera': '霍乱',
    'Dysentery': '痢疾',
    'Bacterial dysentery': '细菌性痢疾',
    'Amoebic dysentery': '阿米巴痢疾',
    'Typhoid': '伤寒',
    'Paratyphoid': '副伤寒',
    'Typhoid fever and paratyphoid fever': '伤寒和副伤寒',
    'Acquired immune deficiency syndrome': '艾滋病',
    'HIV': 'ＨＩＶ',
    'Gonorrhea': '淋病',
    'Syphilis': '梅毒',
    'Tertiary syphilis': 'Ⅲ期梅毒',
    'Secondary syphilis': 'Ⅱ期梅毒',
    'Primary syphilis': 'Ⅰ期梅毒',
    'Congenital syphilis': '胎传梅毒',
    'Latent syphilis': '隐性梅毒',
    'Malaria': '疟疾',
    'Measles': '麻疹',
    'Pertussis': '百日咳',
    'Meningococcal meningitis': '流脑',
    'Scarlet fever': '猩红热',
    'Epidemic hemorrhagic fever': '出血热',
    'Rabies': '狂犬病',
    'Leptospirosis': '钩体病',
    'Brucellosis': '布病',
    'Anthrax': '炭疽',
    'Neonatal tetanus': '新生儿破伤风',
    'Typhus': '斑疹伤寒',
    'Kala azar': '黑热病',
    'Malignant malaria': '恶性疟',
    'Tertian malaria': '间日疟',
    'Malaria (unclassified)': '疟疾（未分型）',
    'Japanese encephalitis': '乙脑',
    'Dengue': '登革热',
    'Tuberculosis': '肺结核',
    'Tuberculosis (rifampicin-resistant)': '利福平耐药',
    'Tuberculosis (unclassified)': '无病原学结果',
    'Tuberculosis (positive)': '病原学阳性',
    'Tuberculosis (negative)': '病原学阴性',
    'Schistosomiasis': '血吸虫病',
    'Echinococcosis': '包虫病',
    'Leprosy': '麻风病',
    'Influenza': '流行性感冒',
    'Mumps': '流行性腮腺炎',
    'Rubella': '风疹',
    'Nongonococcal urethritis': '非淋菌性尿道炎',
    'Infectious diarrhea': '其它感染性腹泻病',
    'Acute hemorrhagic conjunctivitis': '急性出血性结膜炎',
    'Condyloma acuminatum': '尖锐湿疣',
    'Genital herpes': '生殖器疱疹',
    'Hand foot and mouth disease': '手足口病',
    'Cutaneous anthrax': '皮肤炭疽',
    'Other': '其它',
    'Hepatitis A': '甲肝',
    'Hepatitis B': '乙肝',
    'Hepatitis C': '丙肝',
    'Hepatitis D': '丁肝',
    'Hepatitis E': '戊肝',
    'Other hepatitis': '肝炎（未分型）',
    'Chickenpox': '水痘',
    'Streptococcus suis': '人感染猪链球菌',
    'Chlamydia trachomatis': '生殖道沙眼衣原体感染',
    'Fascioliasis': '肝吸虫病',
    'Typhus': '恙虫病',
    # add
    'SARS-CoV': 'SARS',
    'Hepatitis': '肝炎',
    'Poliomyelitis': '脊髓灰质炎', 
    'Human infection with H5N1 virus': '人感染H5N1病毒',
    'Diphtheria': '白喉',
    'Human infection with H7N9 virus': '人感染H7N9病毒',
    'COVID-19': '新冠肺炎',
    'Filariasis': '丝虫病',
    'Total': '合计'
}